//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsDetranChatBot
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", ConfigurationName="wsDetranChatBot.wsChatbotSoap")]
    public interface wsChatbotSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detran.se.gov.br/services/chatbot/efetuarServicoLicenciamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(alerta))]
        System.Threading.Tasks.Task<wsDetranChatBot.efetuarServicoLicenciamentoResponse> efetuarServicoLicenciamentoAsync(wsDetranChatBot.efetuarServicoLicenciamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detran.se.gov.br/services/chatbot/obterEmissaoCrlv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(alerta))]
        System.Threading.Tasks.Task<wsDetranChatBot.obterEmissaoCrlvResponse> obterEmissaoCrlvAsync(wsDetranChatBot.obterEmissaoCrlvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://detran.se.gov.br/services/chatbot/validarServicoLicenciamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(alerta))]
        System.Threading.Tasks.Task<wsDetranChatBot.validarServicoLicenciamentoResponse> validarServicoLicenciamentoAsync(wsDetranChatBot.validarServicoLicenciamentoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class autenticacao
    {
        
        private string loginUsuarioField;
        
        private string senhaUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string loginUsuario
        {
            get
            {
                return this.loginUsuarioField;
            }
            set
            {
                this.loginUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string senhaUsuario
        {
            get
            {
                return this.senhaUsuarioField;
            }
            set
            {
                this.senhaUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class validarServicoLicenciamentoResult
    {
        
        private int codigoRetornoField;
        
        private erro erroField;
        
        private double codSegurancaOutField;
        
        private double renavamOutField;
        
        private string placaField;
        
        private string marcaModeloField;
        
        private string nomeProprietarioField;
        
        private string temRNTRCField;
        
        private string tipoAutorizacaoRNTRCField;
        
        private string nroAutorizacaoRNTRCField;
        
        private string temIsencaoIPVAField;
        
        private string restricaoField;
        
        private double[] anoLicenciamentoField;
        
        private double contadorAnoLicenciamentoField;
        
        private recallPendente recallPendenteField;
        
        private double contadorRegistroField;
        
        private string[] vetDescDebitosField;
        
        private double[] vetValorCotaunicaField;
        
        private double[] vetValorParcela1Field;
        
        private double[] vetValorParcela2Field;
        
        private double[] vetvalorParcela3Field;
        
        private double totalParcela1Field;
        
        private double totalParcela2Field;
        
        private double totalParcela3Field;
        
        private double totalCotaUnicaField;
        
        private double indiceMensagemField;
        
        private double[] vetCodMensagemField;
        
        private string[] vetMensagemDuaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public erro erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double codSegurancaOut
        {
            get
            {
                return this.codSegurancaOutField;
            }
            set
            {
                this.codSegurancaOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double renavamOut
        {
            get
            {
                return this.renavamOutField;
            }
            set
            {
                this.renavamOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string marcaModelo
        {
            get
            {
                return this.marcaModeloField;
            }
            set
            {
                this.marcaModeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string nomeProprietario
        {
            get
            {
                return this.nomeProprietarioField;
            }
            set
            {
                this.nomeProprietarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string temRNTRC
        {
            get
            {
                return this.temRNTRCField;
            }
            set
            {
                this.temRNTRCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string tipoAutorizacaoRNTRC
        {
            get
            {
                return this.tipoAutorizacaoRNTRCField;
            }
            set
            {
                this.tipoAutorizacaoRNTRCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string nroAutorizacaoRNTRC
        {
            get
            {
                return this.nroAutorizacaoRNTRCField;
            }
            set
            {
                this.nroAutorizacaoRNTRCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string temIsencaoIPVA
        {
            get
            {
                return this.temIsencaoIPVAField;
            }
            set
            {
                this.temIsencaoIPVAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string restricao
        {
            get
            {
                return this.restricaoField;
            }
            set
            {
                this.restricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public double[] anoLicenciamento
        {
            get
            {
                return this.anoLicenciamentoField;
            }
            set
            {
                this.anoLicenciamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double contadorAnoLicenciamento
        {
            get
            {
                return this.contadorAnoLicenciamentoField;
            }
            set
            {
                this.contadorAnoLicenciamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public recallPendente recallPendente
        {
            get
            {
                return this.recallPendenteField;
            }
            set
            {
                this.recallPendenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double contadorRegistro
        {
            get
            {
                return this.contadorRegistroField;
            }
            set
            {
                this.contadorRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public string[] vetDescDebitos
        {
            get
            {
                return this.vetDescDebitosField;
            }
            set
            {
                this.vetDescDebitosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public double[] vetValorCotaunica
        {
            get
            {
                return this.vetValorCotaunicaField;
            }
            set
            {
                this.vetValorCotaunicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public double[] vetValorParcela1
        {
            get
            {
                return this.vetValorParcela1Field;
            }
            set
            {
                this.vetValorParcela1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        public double[] vetValorParcela2
        {
            get
            {
                return this.vetValorParcela2Field;
            }
            set
            {
                this.vetValorParcela2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public double[] vetvalorParcela3
        {
            get
            {
                return this.vetvalorParcela3Field;
            }
            set
            {
                this.vetvalorParcela3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public double totalParcela1
        {
            get
            {
                return this.totalParcela1Field;
            }
            set
            {
                this.totalParcela1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double totalParcela2
        {
            get
            {
                return this.totalParcela2Field;
            }
            set
            {
                this.totalParcela2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public double totalParcela3
        {
            get
            {
                return this.totalParcela3Field;
            }
            set
            {
                this.totalParcela3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public double totalCotaUnica
        {
            get
            {
                return this.totalCotaUnicaField;
            }
            set
            {
                this.totalCotaUnicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public double indiceMensagem
        {
            get
            {
                return this.indiceMensagemField;
            }
            set
            {
                this.indiceMensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        public double[] vetCodMensagem
        {
            get
            {
                return this.vetCodMensagemField;
            }
            set
            {
                this.vetCodMensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        public string[] vetMensagemDua
        {
            get
            {
                return this.vetMensagemDuaField;
            }
            set
            {
                this.vetMensagemDuaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class erro : alerta
    {
        
        private string traceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(recallPendente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(erro))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class alerta
    {
        
        private int codigoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class recallPendente : alerta
    {
        
        private recall[] listaRecallField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public recall[] listaRecall
        {
            get
            {
                return this.listaRecallField;
            }
            set
            {
                this.listaRecallField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class recall
    {
        
        private string descricaoField;
        
        private string defeitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string defeito
        {
            get
            {
                return this.defeitoField;
            }
            set
            {
                this.defeitoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class obterEmissaoCrlvResult
    {
        
        private int codigoRetornoField;
        
        private erro erroField;
        
        private double codSegurancaOutField;
        
        private double renavamField;
        
        private string placaOutField;
        
        private string nomeProprietarioField;
        
        private string documentoCRLVePdfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public erro erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double codSegurancaOut
        {
            get
            {
                return this.codSegurancaOutField;
            }
            set
            {
                this.codSegurancaOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double renavam
        {
            get
            {
                return this.renavamField;
            }
            set
            {
                this.renavamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string placaOut
        {
            get
            {
                return this.placaOutField;
            }
            set
            {
                this.placaOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string nomeProprietario
        {
            get
            {
                return this.nomeProprietarioField;
            }
            set
            {
                this.nomeProprietarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string documentoCRLVePdf
        {
            get
            {
                return this.documentoCRLVePdfField;
            }
            set
            {
                this.documentoCRLVePdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
    public partial class efetuarServicoLicenciamentoResult
    {
        
        private int codigoRetornoField;
        
        private erro erroField;
        
        private string cpfProcuradorField;
        
        private double numeroDocumentoField;
        
        private string tipoDocumentoField;
        
        private string corField;
        
        private double[] vetTaxasField;
        
        private string[] vetDescDebitosField;
        
        private double dataProcessamentoField;
        
        private double exercicioField;
        
        private double indField;
        
        private string marcaModeloField;
        
        private string nomeField;
        
        private string placaField;
        
        private double renavamField;
        
        private string tipoField;
        
        private string[] vetValorAField;
        
        private string valorApagarField;
        
        private double vencimentoField;
        
        private string agenciaField;
        
        private string mensagem1Field;
        
        private string mensagem2Field;
        
        private string mensagem3Field;
        
        private string mensagem4Field;
        
        private string mensagem5Field;
        
        private string totalAField;
        
        private string linhaDigField;
        
        private string linhaCodBarraField;
        
        private string codBarraField;
        
        private string asBace1Field;
        
        private double indDescricaoField;
        
        private string[] vetDescInfracaoField;
        
        private double indMensagemField;
        
        private string[] vetDuaMensagemField;
        
        private string chassiSNGField;
        
        private string tituloVencField;
        
        private string datsVencField;
        
        private double indParcField;
        
        private double[] vetDuaParcField;
        
        private string[] vetValorA1ParcField;
        
        private string[] vetLinhaDigParcField;
        
        private string[] vetLinhaCodBarraField;
        
        private string[] vetCodBarraParcField;
        
        private string[] vetASBACE1ParcField;
        
        private string[] vetValorA2ParcField;
        
        private string[] vetValorA3ParcField;
        
        private string[] vetTotalAParcField;
        
        private double[] vetVencimentoParcField;
        
        private string flagParc1AField;
        
        private string flagParc2AField;
        
        private string flagParc3AField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigoRetorno
        {
            get
            {
                return this.codigoRetornoField;
            }
            set
            {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public erro erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cpfProcurador
        {
            get
            {
                return this.cpfProcuradorField;
            }
            set
            {
                this.cpfProcuradorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double numeroDocumento
        {
            get
            {
                return this.numeroDocumentoField;
            }
            set
            {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cor
        {
            get
            {
                return this.corField;
            }
            set
            {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public double[] vetTaxas
        {
            get
            {
                return this.vetTaxasField;
            }
            set
            {
                this.vetTaxasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] vetDescDebitos
        {
            get
            {
                return this.vetDescDebitosField;
            }
            set
            {
                this.vetDescDebitosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double dataProcessamento
        {
            get
            {
                return this.dataProcessamentoField;
            }
            set
            {
                this.dataProcessamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double exercicio
        {
            get
            {
                return this.exercicioField;
            }
            set
            {
                this.exercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double ind
        {
            get
            {
                return this.indField;
            }
            set
            {
                this.indField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string marcaModelo
        {
            get
            {
                return this.marcaModeloField;
            }
            set
            {
                this.marcaModeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string placa
        {
            get
            {
                return this.placaField;
            }
            set
            {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double renavam
        {
            get
            {
                return this.renavamField;
            }
            set
            {
                this.renavamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public string[] vetValorA
        {
            get
            {
                return this.vetValorAField;
            }
            set
            {
                this.vetValorAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string valorApagar
        {
            get
            {
                return this.valorApagarField;
            }
            set
            {
                this.valorApagarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public double vencimento
        {
            get
            {
                return this.vencimentoField;
            }
            set
            {
                this.vencimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string agencia
        {
            get
            {
                return this.agenciaField;
            }
            set
            {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string mensagem1
        {
            get
            {
                return this.mensagem1Field;
            }
            set
            {
                this.mensagem1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string mensagem2
        {
            get
            {
                return this.mensagem2Field;
            }
            set
            {
                this.mensagem2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string mensagem3
        {
            get
            {
                return this.mensagem3Field;
            }
            set
            {
                this.mensagem3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string mensagem4
        {
            get
            {
                return this.mensagem4Field;
            }
            set
            {
                this.mensagem4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string mensagem5
        {
            get
            {
                return this.mensagem5Field;
            }
            set
            {
                this.mensagem5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string totalA
        {
            get
            {
                return this.totalAField;
            }
            set
            {
                this.totalAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string linhaDig
        {
            get
            {
                return this.linhaDigField;
            }
            set
            {
                this.linhaDigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string linhaCodBarra
        {
            get
            {
                return this.linhaCodBarraField;
            }
            set
            {
                this.linhaCodBarraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string codBarra
        {
            get
            {
                return this.codBarraField;
            }
            set
            {
                this.codBarraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string asBace1
        {
            get
            {
                return this.asBace1Field;
            }
            set
            {
                this.asBace1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public double indDescricao
        {
            get
            {
                return this.indDescricaoField;
            }
            set
            {
                this.indDescricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=31)]
        public string[] vetDescInfracao
        {
            get
            {
                return this.vetDescInfracaoField;
            }
            set
            {
                this.vetDescInfracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public double indMensagem
        {
            get
            {
                return this.indMensagemField;
            }
            set
            {
                this.indMensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=33)]
        public string[] vetDuaMensagem
        {
            get
            {
                return this.vetDuaMensagemField;
            }
            set
            {
                this.vetDuaMensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string chassiSNG
        {
            get
            {
                return this.chassiSNGField;
            }
            set
            {
                this.chassiSNGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string tituloVenc
        {
            get
            {
                return this.tituloVencField;
            }
            set
            {
                this.tituloVencField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string datsVenc
        {
            get
            {
                return this.datsVencField;
            }
            set
            {
                this.datsVencField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public double indParc
        {
            get
            {
                return this.indParcField;
            }
            set
            {
                this.indParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=38)]
        public double[] vetDuaParc
        {
            get
            {
                return this.vetDuaParcField;
            }
            set
            {
                this.vetDuaParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=39)]
        public string[] vetValorA1Parc
        {
            get
            {
                return this.vetValorA1ParcField;
            }
            set
            {
                this.vetValorA1ParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=40)]
        public string[] vetLinhaDigParc
        {
            get
            {
                return this.vetLinhaDigParcField;
            }
            set
            {
                this.vetLinhaDigParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=41)]
        public string[] vetLinhaCodBarra
        {
            get
            {
                return this.vetLinhaCodBarraField;
            }
            set
            {
                this.vetLinhaCodBarraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=42)]
        public string[] vetCodBarraParc
        {
            get
            {
                return this.vetCodBarraParcField;
            }
            set
            {
                this.vetCodBarraParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=43)]
        public string[] vetASBACE1Parc
        {
            get
            {
                return this.vetASBACE1ParcField;
            }
            set
            {
                this.vetASBACE1ParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=44)]
        public string[] vetValorA2Parc
        {
            get
            {
                return this.vetValorA2ParcField;
            }
            set
            {
                this.vetValorA2ParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=45)]
        public string[] vetValorA3Parc
        {
            get
            {
                return this.vetValorA3ParcField;
            }
            set
            {
                this.vetValorA3ParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=46)]
        public string[] vetTotalAParc
        {
            get
            {
                return this.vetTotalAParcField;
            }
            set
            {
                this.vetTotalAParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=47)]
        public double[] vetVencimentoParc
        {
            get
            {
                return this.vetVencimentoParcField;
            }
            set
            {
                this.vetVencimentoParcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string flagParc1A
        {
            get
            {
                return this.flagParc1AField;
            }
            set
            {
                this.flagParc1AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string flagParc2A
        {
            get
            {
                return this.flagParc2AField;
            }
            set
            {
                this.flagParc2AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string flagParc3A
        {
            get
            {
                return this.flagParc3AField;
            }
            set
            {
                this.flagParc3AField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="efetuarServicoLicenciamento", WrapperNamespace="http://detran.se.gov.br/services/chatbot/", IsWrapped=true)]
    public partial class efetuarServicoLicenciamentoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
        public wsDetranChatBot.autenticacao autenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=0)]
        public double renavam;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=1)]
        public double codSeguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=2)]
        public string restricao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=3)]
        public double anoExercicioLicenciamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=4)]
        public string tipoAutorizacaoRNTRC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=5)]
        public double nroAutorizacaoRNTRC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=6)]
        public string dataValidadeRNTRC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=7)]
        public string isencaoIPVA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=8)]
        public string tipoDocumentoIn;
        
        public efetuarServicoLicenciamentoRequest()
        {
        }
        
        public efetuarServicoLicenciamentoRequest(wsDetranChatBot.autenticacao autenticacao, double renavam, double codSeguranca, string restricao, double anoExercicioLicenciamento, string tipoAutorizacaoRNTRC, double nroAutorizacaoRNTRC, string dataValidadeRNTRC, string isencaoIPVA, string tipoDocumentoIn)
        {
            this.autenticacao = autenticacao;
            this.renavam = renavam;
            this.codSeguranca = codSeguranca;
            this.restricao = restricao;
            this.anoExercicioLicenciamento = anoExercicioLicenciamento;
            this.tipoAutorizacaoRNTRC = tipoAutorizacaoRNTRC;
            this.nroAutorizacaoRNTRC = nroAutorizacaoRNTRC;
            this.dataValidadeRNTRC = dataValidadeRNTRC;
            this.isencaoIPVA = isencaoIPVA;
            this.tipoDocumentoIn = tipoDocumentoIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="efetuarServicoLicenciamentoResponse", WrapperNamespace="http://detran.se.gov.br/services/chatbot/", IsWrapped=true)]
    public partial class efetuarServicoLicenciamentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=0)]
        public wsDetranChatBot.efetuarServicoLicenciamentoResult efetuarServicoLicenciamentoResult;
        
        public efetuarServicoLicenciamentoResponse()
        {
        }
        
        public efetuarServicoLicenciamentoResponse(wsDetranChatBot.efetuarServicoLicenciamentoResult efetuarServicoLicenciamentoResult)
        {
            this.efetuarServicoLicenciamentoResult = efetuarServicoLicenciamentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterEmissaoCrlv", WrapperNamespace="http://detran.se.gov.br/services/chatbot/", IsWrapped=true)]
    public partial class obterEmissaoCrlvRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
        public wsDetranChatBot.autenticacao autenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=0)]
        public string placa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=1)]
        public double codSeguranca;
        
        public obterEmissaoCrlvRequest()
        {
        }
        
        public obterEmissaoCrlvRequest(wsDetranChatBot.autenticacao autenticacao, string placa, double codSeguranca)
        {
            this.autenticacao = autenticacao;
            this.placa = placa;
            this.codSeguranca = codSeguranca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obterEmissaoCrlvResponse", WrapperNamespace="http://detran.se.gov.br/services/chatbot/", IsWrapped=true)]
    public partial class obterEmissaoCrlvResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=0)]
        public wsDetranChatBot.obterEmissaoCrlvResult obterEmissaoCrlvResult;
        
        public obterEmissaoCrlvResponse()
        {
        }
        
        public obterEmissaoCrlvResponse(wsDetranChatBot.obterEmissaoCrlvResult obterEmissaoCrlvResult)
        {
            this.obterEmissaoCrlvResult = obterEmissaoCrlvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarServicoLicenciamento", WrapperNamespace="http://detran.se.gov.br/services/chatbot/", IsWrapped=true)]
    public partial class validarServicoLicenciamentoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://detran.se.gov.br/services/chatbot/")]
        public wsDetranChatBot.autenticacao autenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=0)]
        public double renavam;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=1)]
        public double codSeguranca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=2)]
        public string tipoDocumentoIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=3)]
        public double anoLicenciamentoIn;
        
        public validarServicoLicenciamentoRequest()
        {
        }
        
        public validarServicoLicenciamentoRequest(wsDetranChatBot.autenticacao autenticacao, double renavam, double codSeguranca, string tipoDocumentoIn, double anoLicenciamentoIn)
        {
            this.autenticacao = autenticacao;
            this.renavam = renavam;
            this.codSeguranca = codSeguranca;
            this.tipoDocumentoIn = tipoDocumentoIn;
            this.anoLicenciamentoIn = anoLicenciamentoIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarServicoLicenciamentoResponse", WrapperNamespace="http://detran.se.gov.br/services/chatbot/", IsWrapped=true)]
    public partial class validarServicoLicenciamentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://detran.se.gov.br/services/chatbot/", Order=0)]
        public wsDetranChatBot.validarServicoLicenciamentoResult validarServicoLicenciamentoResult;
        
        public validarServicoLicenciamentoResponse()
        {
        }
        
        public validarServicoLicenciamentoResponse(wsDetranChatBot.validarServicoLicenciamentoResult validarServicoLicenciamentoResult)
        {
            this.validarServicoLicenciamentoResult = validarServicoLicenciamentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface wsChatbotSoapChannel : wsDetranChatBot.wsChatbotSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class wsChatbotSoapClient : System.ServiceModel.ClientBase<wsDetranChatBot.wsChatbotSoap>, wsDetranChatBot.wsChatbotSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public wsChatbotSoapClient()   
        {
        }
        public wsChatbotSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsChatbotSoapClient.GetBindingForEndpoint(endpointConfiguration), wsChatbotSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsChatbotSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsChatbotSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsChatbotSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsChatbotSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsChatbotSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsDetranChatBot.efetuarServicoLicenciamentoResponse> wsDetranChatBot.wsChatbotSoap.efetuarServicoLicenciamentoAsync(wsDetranChatBot.efetuarServicoLicenciamentoRequest request)
        {
            return base.Channel.efetuarServicoLicenciamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsDetranChatBot.efetuarServicoLicenciamentoResponse> efetuarServicoLicenciamentoAsync(wsDetranChatBot.autenticacao autenticacao, double renavam, double codSeguranca, string restricao, double anoExercicioLicenciamento, string tipoAutorizacaoRNTRC, double nroAutorizacaoRNTRC, string dataValidadeRNTRC, string isencaoIPVA, string tipoDocumentoIn)
        {
            wsDetranChatBot.efetuarServicoLicenciamentoRequest inValue = new wsDetranChatBot.efetuarServicoLicenciamentoRequest();
            inValue.autenticacao = autenticacao;
            inValue.renavam = renavam;
            inValue.codSeguranca = codSeguranca;
            inValue.restricao = restricao;
            inValue.anoExercicioLicenciamento = anoExercicioLicenciamento;
            inValue.tipoAutorizacaoRNTRC = tipoAutorizacaoRNTRC;
            inValue.nroAutorizacaoRNTRC = nroAutorizacaoRNTRC;
            inValue.dataValidadeRNTRC = dataValidadeRNTRC;
            inValue.isencaoIPVA = isencaoIPVA;
            inValue.tipoDocumentoIn = tipoDocumentoIn;
            return ((wsDetranChatBot.wsChatbotSoap)(this)).efetuarServicoLicenciamentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsDetranChatBot.obterEmissaoCrlvResponse> wsDetranChatBot.wsChatbotSoap.obterEmissaoCrlvAsync(wsDetranChatBot.obterEmissaoCrlvRequest request)
        {
            return base.Channel.obterEmissaoCrlvAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsDetranChatBot.obterEmissaoCrlvResponse> obterEmissaoCrlvAsync(wsDetranChatBot.autenticacao autenticacao, string placa, double codSeguranca)
        {
            wsDetranChatBot.obterEmissaoCrlvRequest inValue = new wsDetranChatBot.obterEmissaoCrlvRequest();
            inValue.autenticacao = autenticacao;
            inValue.placa = placa;
            inValue.codSeguranca = codSeguranca;
            return ((wsDetranChatBot.wsChatbotSoap)(this)).obterEmissaoCrlvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsDetranChatBot.validarServicoLicenciamentoResponse> wsDetranChatBot.wsChatbotSoap.validarServicoLicenciamentoAsync(wsDetranChatBot.validarServicoLicenciamentoRequest request)
        {
            return base.Channel.validarServicoLicenciamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsDetranChatBot.validarServicoLicenciamentoResponse> validarServicoLicenciamentoAsync(wsDetranChatBot.autenticacao autenticacao, double renavam, double codSeguranca, string tipoDocumentoIn, double anoLicenciamentoIn)
        {
            wsDetranChatBot.validarServicoLicenciamentoRequest inValue = new wsDetranChatBot.validarServicoLicenciamentoRequest();
            inValue.autenticacao = autenticacao;
            inValue.renavam = renavam;
            inValue.codSeguranca = codSeguranca;
            inValue.tipoDocumentoIn = tipoDocumentoIn;
            inValue.anoLicenciamentoIn = anoLicenciamentoIn;
            return ((wsDetranChatBot.wsChatbotSoap)(this)).validarServicoLicenciamentoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            //if ((endpointConfiguration == EndpointConfiguration.wsChatbotSoap))
            //{
            //    System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            //    result.MaxBufferSize = int.MaxValue;
            //    result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            //    result.MaxReceivedMessageSize = int.MaxValue;
            //    result.AllowCookies = true;
            //    return result;
            //}
            if ((endpointConfiguration == EndpointConfiguration.wsChatbotSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            //if ((endpointConfiguration == EndpointConfiguration.wsChatbotSoap))
            //{
            //    return new System.ServiceModel.EndpointAddress("http://172.28.64.58:9176/homologa/serviceChatBot");
            //}
            if ((endpointConfiguration == EndpointConfiguration.wsChatbotSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.28.64.58:9176/homologa/serviceChatBot");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            //wsChatbotSoap,
            
            wsChatbotSoap12,
        }
    }
}
